[package]
name = "scroll_phat_hd"
version = "0.1.0"
authors = ["Tiziano Santoro <tiziano88@gmail.com>"]
description = "Scroll Phat HD"
license = "MIT"

[dependencies]
termion = "1.0"

[target.'cfg(unix)'.dependencies]
i2cdev = "0.3"
